name: CI

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .Net Core SDK
      uses: actions/setup-dotnet@1.4.0
      with:
        dotnet-version: 3.1.200-preview-014883
      
    - name: Test
      run: dotnet test
      
    - name: Build
      run: dotnet build -c release
